<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>Mikita</PackageId>
		<Version>0.1.0-alpha.2</Version>
		<Authors>Markushonok</Authors>
		<Description>General-purpose library used by Inkraft.</Description>
		<PackageProjectUrl>https://github.com/markushonok/Mikita</PackageProjectUrl>
		<RepositoryUrl>https://github.com/markushonok/Mikita</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Evaluation\Laziness\"/>
		<Folder Include="Graphics\"/>
		<Folder Include="UI\"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NetFabric.Hyperlinq" Version="3.0.0-beta48" />
		<PackageReference Include="Tomlyn" Version="1.2.0" />
	</ItemGroup>
</Project>
